import type { Metadata } from 'next'
import CocktailFacetPage from '@/components/CocktailFacetPage'
import { getFacets } from '@/lib/facet-data'
import { canonicalFor, pageCount, robotsFor, titleFor } from '@/lib/cocktail-facets'
import { OG_IMAGE_COCKTAIL, baseOpenGraph } from '@/lib/og'

const KIND = 'spirit' as const

export const revalidate = 3600

// Every page that exists is generated by number. /page/9/ on a three-page facet
// still 404s, from the bounds check in CocktailFacetPage rather than from the
// router. See the style route for why dynamicParams must stay true.
export async function generateStaticParams() {
  const facets = await getFacets(KIND)
  return facets.flatMap((f) =>
    Array.from({ length: pageCount(f.count) }, (_, i) => i + 1)
      .filter((n) => n > 1)
      .map((n) => ({ value: f.value, n: String(n) }))
  )
}

export const dynamicParams = true

export async function generateMetadata({
  params,
}: {
  params: Promise<{ value: string; n: string }>
}): Promise<Metadata> {
  const { value, n } = await params
  const page = Number(n)
  const facet = (await getFacets(KIND)).find((f) => f.value === value)
  if (!facet) return { title: 'Not Found' }

  return {
    title: titleFor(facet, page),
    // Ahrefs measured the old one-clause version at 74 to 78 characters, short
    // of the 110 a description needs to earn its space in a result. The count
    // and what a reader gets are worth the extra clause.
    description: `${facet.count} ${facet.label.toLowerCase()} cocktail recipes, page ${page} of ${pageCount(facet.count)} from the Jerry Can Spirits Field Manual. Measures, method and the reasoning behind each.`,
    // Self-canonical: page 2 carries recipes page 1 does not, so pointing it at
    // page 1 would ask Google to drop real content.
    alternates: { canonical: `https://jerrycanspirits.co.uk${canonicalFor(facet, page)}` },
    // og:url is required by the Open Graph protocol and was absent, which is
    // why the crawl reported these cards invalid while every other attribute
    // was present. Title and description are left to resolve from the fields
    // above rather than restated here.
    openGraph: {
      ...baseOpenGraph,
      url: `https://jerrycanspirits.co.uk${canonicalFor(facet, page)}`,
      images: OG_IMAGE_COCKTAIL,
    },
    robots: robotsFor(facet),
  }
}

export default async function Page({ params }: { params: Promise<{ value: string; n: string }> }) {
  const { value, n } = await params
  return <CocktailFacetPage kind={KIND} value={value} page={Number(n)} />
}
