import type { Metadata } from 'next'
import Link from 'next/link'
import { baseOpenGraph } from '@/lib/og'

export const metadata: Metadata = {
  title: 'Pour IQ™ — Margin Analysis for Cocktail Menus | Jerry Can Spirits®',
  description:
    'Pour IQ analyses your cocktail menu for margin, ingredient overlap, and waste risk, with AI recommendations grounded in the Jerry Can Spirits Field Manual. Available to trade customers as an additional service.',
  alternates: {
    canonical: 'https://jerrycanspirits.co.uk/trade/pour-iq/',
  },
  openGraph: {
    ...baseOpenGraph,
    title: 'Pour IQ™ — Margin Analysis for Cocktail Menus | Jerry Can Spirits®',
    description:
      'AI margin analysis for cocktail menus. For pubs, bars, restaurants, and hotels.',
    url: 'https://jerrycanspirits.co.uk/trade/pour-iq/',
  },
}

interface FeatureBlock {
  title: string
  description: string
}

const SHIPPED: FeatureBlock[] = [
  {
    title: 'AI menu import',
    description: 'Paste your menu text, upload a PDF, or drop in an Excel/CSV. Claude reads it and pulls every drink with inferred recipes. You review and confirm before anything is saved.',
  },
  {
    title: 'Tenant ingredient library',
    description: 'Add an ingredient once with its cost and bottle size. Reuse it across every drink and every menu. Change the cost in one place when your supplier moves.',
  },
  {
    title: 'Profitability metrics',
    description: 'Per-drink GP and margin, average GP across the menu, ingredient overlap, single-use ingredients flagged as waste risk. The maths, plainly.',
  },
  {
    title: 'Cost-change what-if',
    description: 'Pick an ingredient, dial in a hypothetical new cost, watch the GP shift across every drink that uses it. Useful for supplier negotiations and for deciding whether to absorb a price rise.',
  },
  {
    title: 'Promotional pricing',
    description: 'Set an alternative price per drink for happy hour or 2-4-1 periods. Pour IQ shows the promo GP alongside the standard one so the trade-off is visible. Apply to every drink at once with a bulk percentage off.',
  },
  {
    title: 'VAT-aware GP',
    description: 'Toggle whether your sale prices are inc-VAT (customer-facing) or net of VAT (P&L view). GP recomputes against the right base so the numbers match what your accountant sees.',
  },
  {
    title: 'AI recommendations',
    description: 'Specific, actionable suggestions on pricing, menu balance, and complexity. Written in plain English. Generated by Claude with hospitality context.',
  },
  {
    title: 'Printable report',
    description: 'One click sends the menu analysis to a paper-friendly report. Hand it to the owner, the distributor, or your accountant.',
  },
  {
    title: 'Field Manual links',
    description: 'Drinks on your menu cross-reference our Field Manual. Bartenders get technique, history, and serve detail without searching.',
  },
]

const COMING_SOON: FeatureBlock[] = [
  {
    title: 'Sales volume tracking',
    description: 'Enter how many of each drink sold this period (or paste from your POS export). Pour IQ shows contribution by drink so a high-volume 65% GP cocktail can be ranked above a low-volume 78% GP one — the way real menu decisions actually get made.',
  },
  {
    title: 'Menu version comparison',
    description: 'Duplicate Spring 2026 into Summer 2026. See exactly what changed in GP, which drinks got better, which got worse.',
  },
  {
    title: 'Barcode scanner for ingredients',
    description: 'Scan a bottle with your phone. Library auto-fills on the second scan. No more typing supplier SKUs.',
  },
  {
    title: 'Day-aware promotional periods',
    description: 'Tag promos to specific days or date ranges. The menu detail page knows whether today is a promo day and reports accordingly.',
  },
  {
    title: 'Multi-user accounts',
    description: 'Owner, bar manager, and head chef each get their own access with different permissions. Invite-based, no shared PINs.',
  },
  {
    title: 'POS integration',
    description: 'ePOSnow, Square, and Lightspeed connectors so sales volumes flow in automatically. No more weekly data entry.',
  },
  {
    title: 'Xero integration',
    description: 'Cost updates from supplier invoices flow into the library. Aggregate cost data pushes back to your accountant.',
  },
]

export default function PourIqMarketingPage() {
  return (
    <main className="min-h-screen">
      {/* Hero */}
      <section className="py-20 lg:py-28">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="inline-block px-4 py-2 bg-jerry-green-800/60 backdrop-blur-sm rounded-full border border-gold-500/30 mb-8">
            <span className="text-gold-300 text-sm font-semibold uppercase tracking-widest">Pour IQ™</span>
          </div>
          <h1 className="text-4xl md:text-5xl lg:text-6xl font-serif font-bold text-white mb-6 leading-tight">
            Margin analysis for cocktail menus.
          </h1>
          <p className="text-xl text-parchment-300 max-w-2xl leading-relaxed">
            Pour IQ tells you which cocktails are pulling your margin down, which ingredients carry waste risk, and what to change. Built for venues that want to be deliberate about their menu, not lucky.
          </p>
        </div>
      </section>

      {/* What it does */}
      <section className="py-16 border-t border-gold-500/10">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-2xl font-serif font-bold text-white mb-3">What it does today</h2>
          <p className="text-parchment-400 text-sm mb-12 max-w-2xl">
            Every feature below is live. Pilot venues are using these now.
          </p>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {SHIPPED.map((f) => (
              <div key={f.title}>
                <h3 className="text-gold-400 text-sm font-semibold uppercase tracking-widest mb-3">
                  {f.title}
                </h3>
                <p className="text-parchment-300 text-sm leading-relaxed">
                  {f.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="py-16 border-t border-gold-500/10">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-2xl font-serif font-bold text-white mb-12">How it works</h2>
          <ol className="space-y-8 max-w-2xl">
            <li>
              <p className="text-gold-400 text-xs uppercase tracking-widest mb-2">Step 1</p>
              <h3 className="text-xl font-serif font-bold text-white mb-2">Get your menu in</h3>
              <p className="text-parchment-300 text-sm leading-relaxed">
                Paste menu text, upload a PDF, or drop in an Excel/CSV. Claude reads it and pulls every drink with inferred classic recipes. Review and adjust before anything saves.
              </p>
            </li>
            <li>
              <p className="text-gold-400 text-xs uppercase tracking-widest mb-2">Step 2</p>
              <h3 className="text-xl font-serif font-bold text-white mb-2">See the numbers</h3>
              <p className="text-parchment-300 text-sm leading-relaxed">
                GP per drink, ingredient overlap, waste flags. Sort by margin, see promotional GP alongside standard, flip the menu between inc-VAT and net-of-VAT views.
              </p>
            </li>
            <li>
              <p className="text-gold-400 text-xs uppercase tracking-widest mb-2">Step 3</p>
              <h3 className="text-xl font-serif font-bold text-white mb-2">Model the trade-offs</h3>
              <p className="text-parchment-300 text-sm leading-relaxed">
                Run a what-if on a supplier price change. Apply a 20% bulk promo to every drink and see the GP impact. Generate AI recommendations grounded in your specific menu and the Field Manual.
              </p>
            </li>
            <li>
              <p className="text-gold-400 text-xs uppercase tracking-widest mb-2">Step 4</p>
              <h3 className="text-xl font-serif font-bold text-white mb-2">Print and ship</h3>
              <p className="text-parchment-300 text-sm leading-relaxed">
                One-click printable report for owner conversations. Apply the recommendations you agree with and the maths re-runs immediately.
              </p>
            </li>
          </ol>
        </div>
      </section>

      {/* Coming soon */}
      <section className="py-16 border-t border-gold-500/10">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-2xl font-serif font-bold text-white mb-3">Coming soon</h2>
          <p className="text-parchment-400 text-sm mb-12 max-w-2xl">
            Active roadmap. Pilot feedback drives the order.
          </p>
          <div className="grid md:grid-cols-2 gap-8">
            {COMING_SOON.map((f) => (
              <div key={f.title}>
                <h3 className="text-parchment-200 text-sm font-semibold uppercase tracking-widest mb-3">
                  {f.title}
                </h3>
                <p className="text-parchment-400 text-sm leading-relaxed">
                  {f.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section className="py-16 border-t border-gold-500/10">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-2xl font-serif font-bold text-white mb-4">What it costs</h2>
          <p className="text-parchment-300 text-sm leading-relaxed max-w-2xl">
            Annual licence per venue. We are working through pilots and will publish pricing once it is settled. In the meantime, get in touch and we will talk it through.
          </p>
        </div>
      </section>

      {/* Two-path CTA */}
      <section className="py-16 border-t border-gold-500/10">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid lg:grid-cols-2 gap-6">
            <div className="bg-jerry-green-800/40 border border-gold-500/30 rounded-xl p-8">
              <h3 className="text-xl font-serif font-bold text-white mb-2">New to Jerry Can Spirits?</h3>
              <p className="text-parchment-400 text-sm mb-6">
                Apply for a trade account first. Pour IQ is available as an add-on once your account is live.
              </p>
              <Link
                href="/trade/apply/"
                className="inline-flex items-center px-6 py-3 bg-gold-500 text-jerry-green-900 font-bold rounded-lg hover:bg-gold-400 transition-colors text-sm"
              >
                Apply for a trade account
              </Link>
            </div>
            <div className="bg-jerry-green-800/20 border border-gold-500/20 rounded-xl p-8">
              <h3 className="text-xl font-serif font-bold text-white mb-2">Already a trade customer?</h3>
              <p className="text-parchment-400 text-sm mb-6">
                Get in touch about adding a Pour IQ licence to your account.
              </p>
              <a
                href="mailto:trade@jerrycanspirits.co.uk?subject=Pour%20IQ%20licence%20enquiry"
                className="inline-flex items-center px-6 py-3 bg-gold-500 text-jerry-green-900 font-bold rounded-lg hover:bg-gold-400 transition-colors text-sm"
              >
                Enquire about a licence
              </a>
            </div>
          </div>
        </div>
      </section>
    </main>
  )
}
