import type { Metadata } from 'next'
import Link from 'next/link'
import { baseOpenGraph } from '@/lib/og'

export const metadata: Metadata = {
  title: 'Pour IQ — Margin Analysis for Cocktail Menus | Jerry Can Spirits',
  description:
    'Pour IQ analyses your cocktail menu for margin, ingredient overlap, and waste risk, with AI recommendations grounded in the Jerry Can Spirits Field Manual. Available to trade customers as an additional service.',
  alternates: {
    canonical: 'https://jerrycanspirits.co.uk/trade/pour-iq/',
  },
  openGraph: {
    ...baseOpenGraph,
    title: 'Pour IQ — Margin Analysis for Cocktail Menus | Jerry Can Spirits®',
    description:
      'AI margin analysis for cocktail menus. For pubs, bars, restaurants, and hotels.',
    url: 'https://jerrycanspirits.co.uk/trade/pour-iq/',
  },
}

export default function PourIqMarketingPage() {
  return (
    <main className="min-h-screen">
      {/* Hero */}
      <section className="py-20 lg:py-28">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="inline-block px-4 py-2 bg-jerry-green-800/60 backdrop-blur-sm rounded-full border border-gold-500/30 mb-8">
            <span className="text-gold-300 text-sm font-semibold uppercase tracking-widest">Pour IQ</span>
          </div>
          <h1 className="text-4xl md:text-5xl lg:text-6xl font-serif font-bold text-white mb-6 leading-tight">
            Margin analysis for cocktail menus.
          </h1>
          <p className="text-xl text-parchment-300 max-w-2xl leading-relaxed">
            Pour IQ tells you which cocktails are pulling your margin down, which ingredients carry waste risk, and what to change. Built for venues that want to be deliberate about their menu, not lucky.
          </p>
        </div>
      </section>

      {/* What it does */}
      <section className="py-16 border-t border-gold-500/10">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-2xl font-serif font-bold text-white mb-12">What it does</h2>
          <div className="grid md:grid-cols-3 gap-10">
            <div>
              <h3 className="text-gold-400 text-sm font-semibold uppercase tracking-widest mb-3">
                Profitability metrics
              </h3>
              <p className="text-parchment-300 text-sm leading-relaxed">
                Average GP, best and worst margin cocktails, single-use ingredients flagged as waste risk. The maths, plainly.
              </p>
            </div>
            <div>
              <h3 className="text-gold-400 text-sm font-semibold uppercase tracking-widest mb-3">
                AI recommendations
              </h3>
              <p className="text-parchment-300 text-sm leading-relaxed">
                Specific, actionable suggestions on pricing, menu balance, and complexity. Written in plain English. Generated by Claude with hospitality context.
              </p>
            </div>
            <div>
              <h3 className="text-gold-400 text-sm font-semibold uppercase tracking-widest mb-3">
                Field Manual links
              </h3>
              <p className="text-parchment-300 text-sm leading-relaxed">
                Cocktails on your menu cross-reference our Field Manual. Bartenders get technique, history, and serve detail without searching.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="py-16 border-t border-gold-500/10">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-2xl font-serif font-bold text-white mb-12">How it works</h2>
          <ol className="space-y-8 max-w-2xl">
            <li>
              <p className="text-gold-400 text-xs uppercase tracking-widest mb-2">Step 1</p>
              <h3 className="text-xl font-serif font-bold text-white mb-2">Enter your menu</h3>
              <p className="text-parchment-300 text-sm leading-relaxed">
                Add cocktails one at a time with ingredients, bottle sizes, and costs. Menu import from PDF or photo is on the roadmap.
              </p>
            </li>
            <li>
              <p className="text-gold-400 text-xs uppercase tracking-widest mb-2">Step 2</p>
              <h3 className="text-xl font-serif font-bold text-white mb-2">See the numbers</h3>
              <p className="text-parchment-300 text-sm leading-relaxed">
                GP per cocktail, ingredient overlap, waste flags. Updates in real time as you adjust prices and pours.
              </p>
            </li>
            <li>
              <p className="text-gold-400 text-xs uppercase tracking-widest mb-2">Step 3</p>
              <h3 className="text-xl font-serif font-bold text-white mb-2">Apply the recommendations</h3>
              <p className="text-parchment-300 text-sm leading-relaxed">
                AI surfaces specific changes that improve your margin and reduce complexity. You decide what to ship to the menu.
              </p>
            </li>
          </ol>
        </div>
      </section>

      {/* Pricing */}
      <section className="py-16 border-t border-gold-500/10">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-2xl font-serif font-bold text-white mb-4">What it costs</h2>
          <p className="text-parchment-300 text-sm leading-relaxed max-w-2xl">
            Annual licence per venue. We are working through pilots and will publish pricing once it is settled. In the meantime, get in touch and we will talk it through.
          </p>
        </div>
      </section>

      {/* Two-path CTA */}
      <section className="py-16 border-t border-gold-500/10">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid lg:grid-cols-2 gap-6">
            <div className="bg-jerry-green-800/40 border border-gold-500/30 rounded-xl p-8">
              <h3 className="text-xl font-serif font-bold text-white mb-2">New to Jerry Can Spirits?</h3>
              <p className="text-parchment-400 text-sm mb-6">
                Apply for a trade account first. Pour IQ is available as an add-on once your account is live.
              </p>
              <Link
                href="/trade/apply/"
                className="inline-flex items-center px-6 py-3 bg-gold-500 text-jerry-green-900 font-bold rounded-lg hover:bg-gold-400 transition-colors text-sm"
              >
                Apply for a trade account
              </Link>
            </div>
            <div className="bg-jerry-green-800/20 border border-gold-500/20 rounded-xl p-8">
              <h3 className="text-xl font-serif font-bold text-white mb-2">Already a trade customer?</h3>
              <p className="text-parchment-400 text-sm mb-6">
                Get in touch about adding a Pour IQ licence to your account.
              </p>
              <a
                href="mailto:trade@jerrycanspirits.co.uk?subject=Pour%20IQ%20licence%20enquiry"
                className="inline-flex items-center px-6 py-3 bg-gold-500 text-jerry-green-900 font-bold rounded-lg hover:bg-gold-400 transition-colors text-sm"
              >
                Enquire about a licence
              </a>
            </div>
          </div>
        </div>
      </section>
    </main>
  )
}
