'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { useCookieConsent } from '@/hooks/useCookieConsent';

declare global {
  interface Window {
    zaraz?: {
      consent: {
        setAll: (granted: boolean) => void;
        set: (purposes: Record<string, boolean>) => void;
      };
      track: (eventName: string, data?: Record<string, unknown>) => void;
    };
  }
}

export default function ConsentBanner() {
  const { hasConsented, isLoading, preferences, savePreferences } = useCookieConsent();
  const [showDetails, setShowDetails] = useState(false);
  const [localPreferences, setLocalPreferences] = useState({
    necessary: true,
    analytics: false,
    marketing: false,
  });

  // Sync local preferences with saved preferences when they change
  useEffect(() => {
    setLocalPreferences(preferences);
  }, [preferences]);

  // Don't show banner if user has already consented or while loading
  if (isLoading || hasConsented) {
    return null;
  }

  const updateConsent = (analytics: boolean, marketing: boolean) => {
    // Update Zaraz consent
    if (typeof window !== 'undefined' && window.zaraz?.consent) {
      try {
        // Use the actual Zaraz-assigned purpose IDs from dashboard
        // These IDs are auto-generated by Cloudflare and shown in Settings → Privacy
        window.zaraz.consent.set({
          HYWH: analytics,   // analytics purpose
          Hhik: marketing,   // marketing purpose
          XwpD: true,        // functional purpose (always granted)
        });
      } catch (error) {
        // Fallback: If purposes aren't configured in Zaraz dashboard, use setAll
        console.warn('Zaraz consent purposes not configured. Using setAll fallback.', error);
        if (analytics || marketing) {
          window.zaraz.consent.setAll(true);
        } else {
          window.zaraz.consent.setAll(false);
        }
      }
    }

    savePreferences({
      necessary: true,
      analytics,
      marketing,
    });
  };

  const handleAcceptAll = () => {
    updateConsent(true, true);
  };

  const handleRejectAll = () => {
    updateConsent(false, false);
  };

  const handleAcceptEssential = () => {
    updateConsent(true, false);
  };

  const handleSaveCustom = () => {
    updateConsent(localPreferences.analytics, localPreferences.marketing);
  };

  return (
    <div className="fixed bottom-0 left-0 right-0 bg-jerry-green-800 border-t border-jerry-gold-500/20 p-4 z-50 shadow-lg">
      <div className="container mx-auto max-w-6xl">
        {!showDetails ? (
          <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
            <div className="flex-1">
              <h3 className="text-white font-playfair font-semibold text-lg mb-2">
                Cookie Consent
              </h3>
              <p className="text-white text-sm">
                We use cookies to improve your experience on our site, analyze traffic, and for marketing purposes.{' '}
                <Link href="/cookie-preferences" className="text-jerry-gold-300 hover:text-jerry-gold-200 underline">
                  Manage your preferences
                </Link>
                {' '}or read our{' '}
                <Link href="/cookie-policy" className="text-jerry-gold-300 hover:text-jerry-gold-200 underline">
                  Cookie Policy
                </Link>.
              </p>
            </div>
            <div className="flex flex-col sm:flex-row gap-2 min-w-fit">
              <button
                onClick={() => setShowDetails(true)}
                className="px-4 py-2 text-white border border-jerry-gold-500/50 rounded hover:bg-jerry-gold-500/20 hover:border-jerry-gold-400 hover:scale-105 transition-all text-sm shadow-md"
              >
                Customize
              </button>
              <button
                onClick={handleRejectAll}
                className="px-4 py-2 text-white border border-jerry-gold-500/50 rounded hover:bg-jerry-gold-500/20 hover:border-jerry-gold-400 hover:scale-105 transition-all text-sm shadow-md"
              >
                Reject All
              </button>
              <button
                onClick={handleAcceptEssential}
                className="px-4 py-2 bg-jerry-gold-600 text-white rounded hover:bg-jerry-gold-500 hover:scale-105 transition-all text-sm font-medium shadow-lg"
              >
                Necessary Only
              </button>
              <button
                onClick={handleAcceptAll}
                className="px-4 py-2 bg-jerry-gold-500 text-white rounded hover:bg-jerry-gold-400 hover:scale-105 transition-all text-sm font-medium shadow-lg"
              >
                Accept All
              </button>
            </div>
          </div>
        ) : (
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="text-white font-playfair font-semibold text-lg">
                Cookie Preferences
              </h3>
              <button
                onClick={() => setShowDetails(false)}
                className="text-white hover:text-jerry-gold-100 text-xl hover:scale-110 transition-all"
              >
                ×
              </button>
            </div>
            
            <div className="space-y-3 text-sm">
              <div className="flex items-center justify-between p-3 bg-jerry-green-700/50 rounded">
                <div>
                  <h4 className="text-white font-medium">Essential Cookies</h4>
                  <p className="text-white text-xs">Required for the website to function properly</p>
                </div>
                <div className="text-white bg-jerry-gold-500 px-2 py-1 rounded text-xs font-medium">
                  Always Active
                </div>
              </div>
              
              <div className="flex items-center justify-between p-3 bg-jerry-green-700/30 rounded">
                <div>
                  <h4 className="text-white font-medium">Analytics Cookies</h4>
                  <p className="text-white text-xs">Help us understand how visitors interact with our website</p>
                </div>
                <label className="relative inline-flex items-center cursor-pointer">
                  <input
                    type="checkbox"
                    className="sr-only"
                    checked={localPreferences.analytics}
                    onChange={(e) => setLocalPreferences(prev => ({ ...prev, analytics: e.target.checked }))}
                  />
                  <div className={`w-11 h-6 rounded-full relative transition-all duration-300 hover:scale-105 ${localPreferences.analytics ? 'bg-yellow-500' : 'bg-slate-500'}`}>
                    <div className={`w-5 h-5 bg-white rounded-full absolute top-[2px] transition-all duration-300 ${localPreferences.analytics ? 'left-[22px]' : 'left-[2px]'}`}></div>
                  </div>
                </label>
              </div>
              
              <div className="flex items-center justify-between p-3 bg-jerry-green-700/30 rounded">
                <div>
                  <h4 className="text-white font-medium">Marketing Cookies</h4>
                  <p className="text-white text-xs">Used for social media advertising (Facebook Pixel), email marketing (Klaviyo), customer reviews (Trustpilot), and promotional campaigns</p>
                </div>
                <label className="relative inline-flex items-center cursor-pointer">
                  <input
                    type="checkbox"
                    className="sr-only"
                    checked={localPreferences.marketing}
                    onChange={(e) => setLocalPreferences(prev => ({ ...prev, marketing: e.target.checked }))}
                  />
                  <div className={`w-11 h-6 rounded-full relative transition-all duration-300 hover:scale-105 ${localPreferences.marketing ? 'bg-yellow-500' : 'bg-slate-500'}`}>
                    <div className={`w-5 h-5 bg-white rounded-full absolute top-[2px] transition-all duration-300 ${localPreferences.marketing ? 'left-[22px]' : 'left-[2px]'}`}></div>
                  </div>
                </label>
              </div>
            </div>
            
            <div className="flex justify-end gap-2 pt-2">
              <button
                onClick={handleRejectAll}
                className="px-4 py-2 text-white border border-jerry-gold-500/50 rounded hover:bg-jerry-gold-500/20 hover:border-jerry-gold-400 transition-all text-sm"
              >
                Reject All
              </button>
              <button
                onClick={handleSaveCustom}
                className="px-4 py-2 bg-jerry-gold-600 text-white rounded hover:bg-jerry-gold-500 hover:scale-105 transition-all text-sm font-medium shadow-lg"
              >
                Save Preferences
              </button>
              <button
                onClick={handleAcceptAll}
                className="px-4 py-2 bg-jerry-gold-500 text-white rounded hover:bg-jerry-gold-400 hover:scale-105 transition-all text-sm font-medium shadow-lg"
              >
                Accept All
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}