#!/usr/bin/env node
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));

const content = `// Auto-generated by scripts/wrap-worker.mjs — do not edit directly
export * from './worker.js';
import openNextWorker from './worker.js';

const EDGE_CACHE_PATHS = new Set([
  '/',
  '/offline',
  '/field-manual',
  '/field-manual/cocktails',
  '/field-manual/equipment',
  '/field-manual/ingredients',
]);

const CACHE_TTL = 3600; // 1 hour

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    if (request.method === 'GET' && EDGE_CACHE_PATHS.has(url.pathname)) {
      const cache = caches.default;
      const cachedResponse = await cache.match(request);

      if (cachedResponse) {
        const headers = new Headers(cachedResponse.headers);
        headers.set('X-Edge-Cache', 'HIT');
        return new Response(cachedResponse.body, { status: cachedResponse.status, headers });
      }

      const response = await openNextWorker.fetch(request, env, ctx);

      if (response.status === 200) {
        const cloned = response.clone();
        const headers = new Headers(cloned.headers);
        headers.set('Cache-Control', \`public, max-age=\${CACHE_TTL}, s-maxage=\${CACHE_TTL}, stale-while-revalidate=86400\`);
        ctx.waitUntil(
          cache.put(request, new Response(cloned.body, { status: cloned.status, headers }))
        );
      }

      return response;
    }

    return openNextWorker.fetch(request, env, ctx);
  },
};
`;

writeFileSync(join(__dirname, '../.open-next/worker-cached.mjs'), content);
console.log('✓ Edge cache wrapper written to .open-next/worker-cached.mjs');
