import type { Metadata } from 'next'
import CocktailFacetPage from '@/components/CocktailFacetPage'
import { getFacets } from '@/lib/facet-data'
import { canonicalFor, pageCount, robotsFor, titleFor } from '@/lib/cocktail-facets'

const KIND = 'style' as const

export const revalidate = 3600

// Every page that exists is generated by number, so /page/9/ on a three-page
// facet 404s instead of rendering an empty grid under a real-looking URL.
export async function generateStaticParams() {
  const facets = await getFacets(KIND)
  return facets.flatMap((f) =>
    Array.from({ length: pageCount(f.count) }, (_, i) => i + 1)
      .filter((n) => n > 1)
      .map((n) => ({ value: f.value, n: String(n) }))
  )
}

export const dynamicParams = false

export async function generateMetadata({
  params,
}: {
  params: Promise<{ value: string; n: string }>
}): Promise<Metadata> {
  const { value, n } = await params
  const page = Number(n)
  const facet = (await getFacets(KIND)).find((f) => f.value === value)
  if (!facet) return { title: 'Not Found' }

  return {
    title: titleFor(facet, page),
    description: `${facet.label} cocktail recipes from the Jerry Can Spirits Field Manual, page ${page} of ${pageCount(facet.count)}.`,
    // Self-canonical: page 2 carries recipes page 1 does not, so pointing it at
    // page 1 would ask Google to drop real content.
    alternates: { canonical: `https://jerrycanspirits.co.uk${canonicalFor(facet, page)}` },
    robots: robotsFor(facet),
  }
}

export default async function Page({ params }: { params: Promise<{ value: string; n: string }> }) {
  const { value, n } = await params
  return <CocktailFacetPage kind={KIND} value={value} page={Number(n)} />
}
